# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Data Experts Group
email: info@dataexpertsgroup.com
description: > # Do you trust your data... The Data Experts Group help to developers, data scients and analysts better understand, process and leverage data.
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://dataexpertsgroup.com" # the base hostname & protocol for your site
twitter_username: DataExperts
github_username:  DataExperts

# Build settings
markdown: kramdown
